site_name: HedgeDocs
site_url: https://hedgedocs.github.io/
github_repo: https://github.com/hedgedocs/hedgedocs.github.io
site_description: Sonic the Hedgehog modding guides and tools
nav:
  - Home: index.md
  - Tools:
    - tools/index.md
    - Sonic Generations: 
      - Lighting/GI: tools/blueblur/lighting.md
      - File Formats: tools/blueblur/files.md
      - Audio: tools/blueblur/audio.md
      - Level Editing: tools/blueblur/levels.md
    - Sonic The Hedgehog (2006):
      - File Formats: tools/marathon/files.md
  - Guides:
    - guides/index.md
    - Sonic Generations: 
      - Lighting/GI:
        - Example Guide: guides/blueblur/lighting/example.md
      - File Formats:
        - XNCP Animations: guides/blueblur/files/xncp_anims.md
      - Audio:
        - Example Guide: guides/blueblur/audio/example.md
      - Level Editing:
        - Sonic GLvl: guides/blueblur/levels/glvl.md
      - Misc:
        - Example Guide: guides/blueblur/misc/example.md
    - Sonic The Hedgehog (2006):
      - Level Editing:
        - Sonic GLvl: guides/marathon/levels/glvl.md
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - git-revision-date-localized:
      type: timeago
      exclude:
        - index.md
theme:
  logo: assets/icon.svg
  favicon: assets/favicon.png
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode