site_name: HedgeDocs
site_url: https://hedgedocs.github.io/
nav:
  - Home: index.md
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.indexes
  palette:
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
