name: push-mkdocs-build
on:
  push:
    paths:
      - hedgedocs/**
    branches:
      - main
  workflow_dispatch:

env:
  ENABLE_GIT_PLUGINS: True

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install lxml
      - run: pip install mkdocs-git-committers-plugin-2
      - run: mkdocs gh-deploy --force
